// Generated by https://quicktype.io

export type Category =
  | 'Animals'
  | 'Anime'
  | 'Anti-Malware'
  | 'Art & Design'
  | 'Authentication'
  | 'Blockchain'
  | 'Books'
  | 'Business'
  | 'Calendar'
  | 'Cloud Storage & File Sharing'
  | 'Continuous Integration'
  | 'Cryptocurrency'
  | 'Currency Exchange'
  | 'Data Validation'
  | 'Development'
  | 'Dictionaries'
  | 'Documents & Productivity'
  | 'Email'
  | 'Entertainment'
  | 'Environment'
  | 'Events'
  | 'Finance'
  | 'Food & Drink'
  | 'Games & Comics'
  | 'Geocoding'
  | 'Government'
  | 'Health'
  | 'Jobs'
  | 'Machine Learning'
  | 'Music'
  | 'News'
  | 'Open Data'
  | 'Open Source Projects'
  | 'Patent'
  | 'Personality'
  | 'Phone'
  | 'Photography'
  | 'Programming'
  | 'Science & Math'
  | 'Security'
  | 'Shopping'
  | 'Social'
  | 'Sports & Fitness'
  | 'Test Data'
  | 'Text Analysis'
  | 'Tracking'
  | 'Transportation'
  | 'URL Shorteners'
  | 'Vehicle'
  | 'Video'
  | 'Weather';

export interface Response {
  count: number;
  entries: Entry[];
}

export interface Entry {
  API: string;
  Description: string;
  Auth: Auth;
  HTTPS: boolean;
  Cors: Cors;
  Link: string;
  Category: Category;
}

export enum Auth {
  APIKey = 'apiKey',
  Empty = '',
  OAuth = 'OAuth',
  UserAgent = 'User-Agent',
  XMashapeKey = 'X-Mashape-Key',
}

export enum Cors {
  No = 'no',
  Unknown = 'unknown',
  Yes = 'yes',
}
